apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  fake-gpu.yaml: |-
  {{ .Files.Get "files/fake-gpu.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-musa-configmap
data:
  fake-musa.yaml: |-
  {{ .Files.Get "files/fake-musa.yaml" | indent 4 }}
