name: Build and Push Container Images

on:
  push:
    branches:
      - main
      - release-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

env:
  REGISTRY: ghcr.io
  REGISTRY_USER: ${{ github.repository_owner }}
  REGISTRY_PATH: ${{ github.repository }}

jobs:
  build-and-publish-images:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build images
        run: |
          sed -i '6,7d' Dockerfile
          IMAGE_REPOSITORY=$(echo "${{ env.REGISTRY_USER }}" | tr '[:upper:]' '[:lower:]')
          make images BUILD_TYPE=Release IMAGE_REPOSITORY="$IMAGE_REPOSITORY"

      - name: Log in to registry
        run: |
          REGISTRY_USER_LC=$(echo "${{ env.REGISTRY_USER }}" | tr '[:upper:]' '[:lower:]')
          echo "${{ secrets.GITHUB_TOKEN }}" | \
              docker login ${{ env.REGISTRY }} -u "$REGISTRY_USER_LC" --password-stdin

      - name: Push images
        run: |
          GITREF=${{ github.ref }}
          REGISTRY_USER_LC=$(echo "${{ env.REGISTRY_USER }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_LOCATION=${{ env.REGISTRY }}/$REGISTRY_USER_LC
          img=fake-gpu
          cd output/
          echo "- Publishing image for tarball $img..."
          docker load -i $img.tar
          echo "  - image:  $img"
          echo "  - digging out tag from git ref $GITREF..."
          case $GITREF in
              refs/tags/v*)
                  tag="${GITREF#refs/tags/}"
                  ;;
              refs/heads/main)
                  tag=unstable
                  ;;
              refs/heads/release-*)
                  tag="${GITREF#refs/heads/release-}-unstable"
                  ;;
              *)
                  echo "error: can't determine tag."
                  exit 1
                  ;;
          esac
          echo "  - tag: $tag"
          docker tag $REGISTRY_USER_LC/$img $IMAGE_LOCATION/$img:$tag
          docker push $IMAGE_LOCATION/$img:$tag